spring.application.name=operaciones
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5435/dogsitter
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
