server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # Enrutamiento para Microservicio de Usuarios
        - id: ms-usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/usuarios/**, /api/v1/clientes/**, /api/v1/empleados/**, /api/v1/mascotas/**
            
        # Enrutamiento para Microservicio de Catálogos
        - id: ms-catalogo
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/catalogo/**

        # Enrutamiento para Microservicio de Eventos
        - id: ms-eventos
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/eventos/**

        # Enrutamiento para Microservicio de Operaciones
        - id: ms-operaciones
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/operaciones/**, /api/v1/menus/**
