server.port=8081

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/db_eventos
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA / Hibernate ───────────────────────────────────────────────────────────
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ─── URLs de otros microservicios ─────────────────────────────────────────────
microservicio.usuarios.url=http://${MS_USUARIOS_HOST:localhost}:8081
microservicio.catalogo.url=http://${MS_CATALOGO_HOST:localhost}:8082