import { EventRequest, Recipe } from './types';

export const INITIAL_REQUESTS: EventRequest[] = [
  {
    id: 'EVT-4829',
    title: 'Picknic de Puppaccinos en Central Park',
    status: 'Pending',
    requesterName: 'Sarah Jenkins',
    requesterEmail: 'sarah.j@example.com',
    requesterPhone: '(555) 123-4567',
    requesterTier: 'Cliente',
    requesterAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    date: '2024-10-15',
    time: '10:00',
    location: 'Central Park, NY',
    dogs: 30,
    humans: 45,
    cakeType: 'peanut_butter',
    pupcakes: 12,
    meatballs: 40,
    humanFood: 'finger_food',
    includeAlcohol: false,
    dogSize: 'medium',
    smallDogs: 10,
    mediumDogs: 15,
    largeDogs: 5,
    specialNotes: 'Buscamos organizar nuestra reunión de otoño anual para el club local de Golden Retrievers. Necesitamos suficientes áreas de sombra y estaciones de agua. Nos enfocamos en premios orgánicos a base de calabaza para los perros y refrigerios ligeros para los dueños.',
    dietaryAlerts: '3 perros son alérgicos al pollo; 1 requiere dieta estrictamente libre de granos.',
    venueRequirements: 'Se requiere perímetro completamente cercado. Acceso a manguera/agua potable.',
    medicalStandby: true
  },
  {
    id: 'EVT-4830',
    title: 'Caminata de Caridad Paws & Pints',
    status: 'Pending',
    requesterName: 'Local Brews Co.',
    requesterEmail: 'events@localbrews.co',
    requesterPhone: '(555) 678-1234',
    requesterTier: 'Cliente Comercial • Miembro del Club',
    requesterAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    date: '2024-11-02',
    time: '14:00',
    location: 'Terraza de Cervecería Local Brews',
    dogs: 120,
    humans: 180,
    cakeType: 'pumpkin_apple',
    pupcakes: 150,
    meatballs: 150,
    humanFood: 'sliders',
    includeAlcohol: true,
    dogSize: 'medium',
    smallDogs: 50,
    mediumDogs: 40,
    largeDogs: 30,
    specialNotes: 'Gran caminata de recaudación de fondos para el vecindario que termina en nuestra terraza de cerveza apta para mascotas. Necesitamos premios orgánicos deliciosos para las colas felices.',
    dietaryAlerts: 'Mantener las golosinas libres de maní por seguridad compartida; seleccionar proteínas aptas para alérgicos.',
    venueRequirements: 'Zona al aire libre segura para perros. Múltiples fuentes de agua.',
    medicalStandby: true
  },
  {
    id: 'EVT-4831',
    title: 'Serie de Talleres de Entrenamiento de Cachorros',
    status: 'Pending',
    requesterName: 'David Chen',
    requesterEmail: 'david.c@example.com',
    requesterPhone: '(555) 612-4911',
    requesterTier: 'Miembro de Nivel Premium',
    requesterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    date: '2024-10-20',
    time: '11:00',
    location: 'Gimnasio Cubierto de Westside',
    dogs: 15,
    humans: 25,
    cakeType: 'none',
    pupcakes: 20,
    meatballs: 30,
    humanFood: 'finger_food',
    includeAlcohol: false,
    dogSize: 'small',
    smallDogs: 10,
    mediumDogs: 3,
    largeDogs: 2,
    specialNotes: 'Curso de obediencia enfocado en cachorros recién adoptados de menos de 12 meses. Los premios de motivación son fundamentales para mantener la energía de los cachorros.',
    dietaryAlerts: 'Todos los cachorros requieren estrictamente proteínas deshidratadas de un solo ingrediente de alta calidad.',
    venueRequirements: 'Pista cerrada de entrenamiento con baldosas de goma antideslizantes.',
    medicalStandby: false
  },
  {
    id: 'EVT-4832',
    title: 'Día de Terapia con Mascotas Corporativa',
    status: 'Pending',
    requesterName: 'Recursos Humanos Intercorp',
    requesterEmail: 'wellbeing@intercorp.org',
    requesterPhone: '(555) 231-5582',
    requesterTier: 'Cliente',
    requesterAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    date: '2025-06-22',
    time: '13:00',
    location: 'Patio Central de Intercorp',
    dogs: 12,
    humans: 80,
    cakeType: 'beef_liver',
    pupcakes: 24,
    meatballs: 40,
    humanFood: 'sliders',
    includeAlcohol: false,
    dogSize: 'large',
    smallDogs: 2,
    mediumDogs: 2,
    largeDogs: 8,
    specialNotes: 'Evento de bienestar para empleados donde traerán perros de terapia personales al patio de la empresa. Requiere una revisión inmediata ya que las aprobaciones corporativas toman tiempo.',
    dietaryAlerts: 'Se prefieren golosinas a base de res y libres de gluten.',
    venueRequirements: 'Cercado temporal de doble puerta, áreas con cenadores sombreados.',
    medicalStandby: true
  }
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'REC-2049',
    name: 'Cupcake de Salmón',
    type: 'Pesquetariano',
    status: 'Active',
    description: 'Una receta base balanceada e hipoalergénica adecuada para estómagos sensibles. Utilizada como base para menús de eventos pesquetarianos.',
    ingredients: [
      { id: '1', name: 'Salmón Salvaje de Alaska', quantity: 450, unit: 'g' },
      { id: '2', name: 'Puré de Camote', quantity: 200, unit: 'g' },
      { id: '3', name: 'Harina de Coco', quantity: 50, unit: 'g' }
    ]
  },
  {
    id: 'REC-2050',
    name: 'Albóndigas de Res',
    type: 'Alto en Proteína',
    status: 'Active',
    description: 'Sabrosas albóndigas hechas con carne de res molida magra orgánica de alta calidad, mezcladas con harina de avena y perejil para un aliento fresco.',
    ingredients: [
      { id: '1', name: 'Carne de Res Molida Premium', quantity: 600, unit: 'g' },
      { id: '2', name: 'Harina de Avena Orgánica', quantity: 150, unit: 'g' },
      { id: '3', name: 'Perejil Picado', quantity: 30, unit: 'g' }
    ]
  },
  {
    id: 'REC-2051',
    name: 'Tazón de Pavo y Quinoa',
    type: 'Balanceado',
    status: 'Active',
    description: 'Una comida completa llena de energía que presenta pechuga de pavo desmenuzada (alternativa segura al pollo propenso a alergias) mezclada con quinoa orgánica y vegetales vibrantes.',
    ingredients: [
      { id: '1', name: 'Pavo Desmechado Apto para Alérgicos', quantity: 500, unit: 'g' },
      { id: '2', name: 'Quinoa Blanca Orgánica', quantity: 300, unit: 'g' },
      { id: '3', name: 'Zanahorias y Guisantes Orgánicos en Cubitos', quantity: 120, unit: 'g' }
    ]
  }
];
